# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: SuperNURDs
# Description of the Site
description: FIRST Robotics Competition Team 3255
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: FRC, FIRST, 3255, frc3255, SuperNURDs
# URL for the Image of custom Favicon
favicon-url: "data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAABgGlDQ1BzUkdCIElFQzYxOTY2LTIuMQAAKM+Vkd8rg1EYxz82mpgIFy5cvAlXJqaGG2VLKGnNlOFme/duU9u8ve+k5Va5VZS48euCv4Bb5VopIiWXck3coNfz2mpL7cI5nef5nO85z9N5ngOOcFrNmNV9kMnmjNC4X5mLzCuuZxw042QQJaqa+mgwOEXF8XFHle1vPHYu/jfq45qpQlWt8IiqGznhCeGp1Zxu87Zwq5qKxoVPhXsMeaDwra3HCvxic7LAXzYb4VBAamsSVpJlHCtjNWVkhKVyOjPpFbX4HrsSt5adnRHfIasdkxDj+FGYZIwAPvoZFuvDg5de2VEhvu83fppliVXF6uQxWCJJihw9oq5Idk18QnRNZpq83f+/fTUTA95Cdrcfap4s660LXFvwvWlZn4eW9X0Ezke4yJbilw9g6F30zZLWuQ+N63B2WdJiO3C+AW0PetSI/kpOWY5EAl5PoCECLddQt1DoWfGc43sIr8lXXcHuHnTL/cbFH2mqZ+fLrSYTAAAACXBIWXMAAC4iAAAuIgGq4t2SAAAFOUlEQVRYR+2YWWwbVRSGM15iJ45jT3koDxVLWYWoBAiQAFHBC4gWgdjFC0UgIfGCxAvigfKAhFQEYlGQEE8QQdVSCqEsJS20ymI7bVYnTpqUptljx04IpCQppGnM/4/PnYwntokgSSuUI32q77n3nvN35txlUrRu63ax2kRogxe8DvauMu8Cv6RdnmGCB/wA0mtEHfBJ+sKGgcXgACeOfRv8telaV6j3VV8j27lIVAVTjZud4cYrnRGSPBicUn39u8ra4WOf2U/63ihrNWPUm7GOglKRkdswwAX2c8LY98HfwqXaLyGn9jt/05eP6D3FNRiXJon9gYTyJ6uDf8A3pfoUXU95a9WY2MOeWswZk/Zh4BU52YYOJ9jDgXwKYZ/WzWCdj3rMYPmI7wvEVXKrQBK9d1G8wiqw+QZXfdir9fNNiO8g8IisjMHhAJUckKzWpyN+rUsFY5t+QrEhtxYPebSBjm2eGuUnkXJHB8fbBfLpwz+j4hG7QPrCJVovS0r8LDG3EqeBj9mROqzPRAKOmBmsWBumnwy+7+80/cLJF0vDqr/rSW8dfXaBpO0Od9ZTzCWQsKQs5bQPuCjwbTpSP+tnGzY4otZAaLfJ4HTPCyUhax+JBB0dqr//zbI2+uw1yH8T3wTH0XdWzcsnkKC0eiwLrZICP2BjsMJ/AgPmrYPx2mIyMN393FKBYCb2oKc2tt1T03KTe8kTbL+v2CyDlpsz/aSQQHJ6p69Z+isokCv3EB3dO7JFoC5OycB06qg+pxZOIawCUa9JVVfxLwMJ9M9xTCGBHQ+YtV0NXKoOg6CbHW13umstEyYn6jKBCMvgxDMl9ZGy/EKzBDq1M213uc2nqMTkE9h0vate9sUuEDDEKYPjKjBBQccvcx5Tkwbe8Zt1ZmXoo/Ke5huN4FkrFALVnsY298FpVfjxPYFhtOdzCWy4xNE6XqPPwzcONousbEPHVjCHJ/Wn2moadEd76id9lsFyMbo7MITV18uxJPFV0C7Q2AuVr/FqZ8guEKV0Ovlj8Azac+BukZPbMOBZThw7gLeObUZERguJ5PaEsaP5BIIptaJHPi3v63ray7PXGBPdWlwT3xsYkfYOkVHYMPAtThj5pLyPwZkEu/0A/ud1KpEdFjfH2QRO00c67l/c2Llg1G8uPvm9S9L/s2EwT5YqTpT97ZxKBGZYzIPv+TslsIHsdefyCQSTyUP6jHWOBeZySPrlGSb4gHHr6Hk+5x7IE8KsJYIjcNgmMGsBxR7Kea4zx/KuWnbDxE0gzkCsFWsyYWEIq5n9hMVeSGDIpY1zq1L9gLE3Sbp/ZwhwK5jl9tN4hTOSlRBY73Y8pgoKBDyRpJ9Cb5M0/80Q6HEGNbYfHH/WhFxIRkJssFjJIxCYNNo5BHI7siyyJyT8yhgCvsbAOLomUWtDTNhyy2INjlSW99OX+DpL4KwSh9ebin8RMMoF7JSwK2cIymvZ50zAbYKCJJlB52Ne44jMI3B26EO/cZSC3UCTsCtrCMwvvQZJZMJLLRdIDoG8Yi2cesV3XHwRkPtKv1KGBBvBoCRMj9fqC8cudTTJk1oisPMRc2vhnI0SZnUNibYAnp1pPh0lzi6w9XbUaOZ2woWxRaavjSHhNnCeAvjZaQqsWhQoV7XzYLtMW1tD4pcoJHVE/4vX/yUCM7wswy+MQUAFhYx9Z2w/AzaB/BhbnRW7XIMAfjIYfyYZ/SwwYNmIj4DMp+OFNgjxg6gIIyeBLt0Xh0EQLxa8ePIj6RpxX1wGYZeD66S5buv2P7Cior8Bg1YSQgOEUUYAAAAASUVORK5CYII="

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/SuperNURDs/TeamPhoto.png

# Social Media and Contact
email: frcteam3255@gmail.com
github_username:  frcteam3255
instagram_username: frcteam3255
facebook_username: team3255sphssupernurds
linkedin_username: frc-team-3255-the-supernurds
youtube_channel_id: "FRC3255"
tba_team: 3255
# twitter_username: 

# Google Analytics
# google-analytics: UA-XXXXXXXXX-X

# Name of the Author
author-name: FRC Team 3255 | SuperNURDs
# URL for the Image of the Author
author-image: /assets/images/SuperNURDs/SNLogo.png
# 60 Words About the Author
author-about: We are a FIRST Robotics Competition (FRC) team based out of San Pasqual High School in Escondido, CA.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/frcteam3255

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
